<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Tündür</title>
</head>
<body>
    <div style="text-align:center;">
        <h1>Reset your password on Tündür.</h1>
        <p style="font-weight: bold;">Your password rest request is processed. Please reset your password to use your account by clicking below button.</p>
        <p>
        
        </p>
        <br><br>
        <a style="border: 1px solid #E22C5E;
        background: #E22C5E;
        text-decoration: none;
        color: #fff;
        padding: 15px;
        margin: 15px auto;" href="{{ route('companyResetPassword') }}/?email={{urlencode($details['email'])}}&token={{urlencode($details['password_reset_token'])}}">Reset Password</a>
        <br><br>
        <p>Thank you</p>
        <p>Tündür</p>
    </div>
</body>
</html> 