<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Tündür Contact Us Form</title>
</head>
<body>
    <h1>{{ $data['title'] }}</h1>
    <p style="font-weight: bold;">{{ $data['description'] }}</p>
    <br><br>
    <br><br>
    <p>Thank you</p>
    <p>Tündür</p>
</body>
</html> 