<!DOCTYPE html>
<html>

<head>
    <title>This Email generated by Tündür</title>
</head>

<body>
    <p style="font-weight: bold;">Please use {{ $details['otp'] }} as OTP to verify your email "{{ $details['email'] }}".</p>
    <br><br>
    <p>Thank you</p>
    <p>Tündür</p>
</body>

</html>
