<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Tündür</title>
</head>
<body>
    <h1>{{ $details['title'] }}</h1>
    <p style="font-weight: bold;">You just registered your email "{{ $details['user']['email'] }}" with Tündür. Please verify your email to use your account by clicking below button</p>
    <br><br>
    <a style="border: 1px solid #E22C5E;
    background: #E22C5E;
    text-decoration: none;
    color: #fff;
    padding: 15px;
    margin: 15px auto;" href="{{url('email/verify')}}/{{$details['user']['email_verification_token']}}">VERIFY YOUR EMAIL</a>
    <br><br>
    <p>Thank you</p>
    <p>Tündür</p>
</body>
</html> 