<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Tündür</title>
</head>
<body>
    <h1>{{ $details['title'] }}</h1>
    <p style="font-weight: bold;">{{ $details['otp'] }}</p>
    <p>Thank you</p>
</body>
</html> 